image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "C:\\Python38-x64"    # available on VS 2017 and 2019

build_script:
- cmd: >-
    mkdir build

    cd build

    "%PYTHON%\\python.exe" -m venv virtual_env

    virtual_env\\Scripts\\activate.bat

    python --version

    pip install conan

    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Scripts

    cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Debug

